apiVersion: apps/v1
kind: Deployment

metadata:
  name: gitops-demo-deployment

spec:
  replicas: 2

  selector:
    matchLabels:
      app: gitops-demo

  template:
    metadata:
      labels:
        app: gitops-demo

    spec:
      containers:
      - name: gitops-demo-container
        image: shaikabdulrasheeq/gitops-demo:v1
       

        ports:
        - containerPort: 5000
